contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.find_all_contact, name= 'index'),
    path('<int:contact_id>/', views.find_contact_by_id, name='contact'),
    path('search/', views.search_contact, name='search')
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', include('contact.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(max_length=50)
    
    class Meta:
        db_table = 'tb_category'
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self) -> str:
        return f'{self.name}'


class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/', null=True)
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    
    class Meta:
        db_table = 'tb_contact'

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'
    
    def name(self) -> str:
        return f'{self.first_name} {self.last_name}'

contact/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'contact/index.html')

contact/views/contact_views.py
from django.shortcuts import redirect, render, get_object_or_404, get_list_or_404
from contact.models import Contact
from django.db.models import Q
from django.core.paginator import Paginator

def find_all_contact(request):
    contacts = Contact.objects.filter(show=True).order_by('id')
    paginator = Paginator(contacts, 10)
    page = request.GET.get('page')
    page_obj = paginator.get_page(page)
    return render(request, 'contact/index.html', context = {'page_obj': page_obj})

def search_contact(request):
    search = request.GET.get('q','')
    if search:
        redirect('contact:index')
    contacts = Contact.objects.filter(
        Q(first_name__icontains=search) |
        Q(id__icontains=search)
    )
    paginator = Paginator(contacts, 10)
    page = request.GET.get('page')
    page_obj = paginator.get_page(page)
    return render(request, 'contact/index.html', context = {'page_obj': page_obj})


def find_contact_by_id(request, contact_id):
    single_contact = get_object_or_404(Contact, id=contact_id)
    return render(request, 'contact/contact.html', context={'contact': single_contact})

contact/templates/contact/contact.html
{% extends "global/base.html" %}

{% block content %}
    <div class="single-contact">
        <img class="contact-img" src="{{ contact.picture }}" alt="picture">
        <h1 class = "single-contact-name">
            {{ contact.name }}
        </h1>
        <p><b>ID:</b> {{ contact.id }}</p>
        <p><b>Email:</b> {{ contact.email }}</p>
        <p><b>Telefone:</b> {{ contact.phone }}</p>
        <p><b>Dia de Criação:</b> {{ contact.created_date }}</p>
        <p><b>Categoria:</b> {{ contact.category.name }}</p>
    </div>

{% endblock content %}

contact/templates/contact/index.html
{% extends 'global/base.html' %}

{% block content %}
{% if  page_obj %}
  <div class="responsive-table">
    <table class="contacts-table">
      <caption class="table-caption ">
        Contacts
      </caption>

      <thead>
        <tr class="table-row table-row-header">
          <th class="table-header">ID</th>
          <th class="table-header">Name</th>
          <th class="table-header">Phone</th>
          <th class="table-header">E-mail</th>
        </tr>
      </thead>

      <tbody>
        {% for contact in page_obj %}
          <tr class="table-row">
            <td class="table-cel">
              <a href="{% url 'contact:contact' contact.id %}">
                {{ contact.id }}
              </a>
            </td>
            <td class="table-cel">
              {{ contact.name }}
            </td>
            <td class="table-cel">
              {{ contact.phone }}
            </td>
            <td class="table-cel">
              {{ contact.email }}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% else %}
<div class="single-contact">
  <h1 class = "single-contact-name">
      Nenhum contato encontrado
  </h1>
</div>
{% endif %}
{% endblock content %}